#!/usr/bin/env bash
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$current_branch" = "main" ]]; then
  echo "You really don't want to push this branch. Aborting."
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Running the Flutter analyzer'
flutter analyze
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Flutter analyzer error'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter analyzer'

printf "\e[33;1m%s\e[0m\n" 'Running unit tests'
flutter test
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Unit tests error'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running unit tests'