#!/usr/bin/env bash

isMerge=$(git rev-parse -q --verify MERGE_HEAD)
if [ -n "$isMerge" ]; then
  exit
fi

dart fix --apply

exts="\.\(dart\)$"
echo "Pre-commit: formatting changed files"

exclude_dir="lib/app/utils/translation/generated"

for file in $(git diff --cached --name-only --diff-filter=ACMR | grep $exts); do
    if [[ $file == $exclude_dir* ]]; then
        echo "Skipping formatting for $file"
        continue
    fi
    echo "Formatting $file"
    dart format --line-length=120 "$file"
    git add "$file"
done