include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/**/generated
    - lib/**/injectable.config.dart
    - test/**/*.mocks.dart
    - test/generate_mocks.mocks.dart

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - sort_constructors_first
    - prefer_relative_imports
    - directives_ordering
    - require_trailing_commas
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - avoid_void_async
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures