include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/app/utils/translations/generated/*.dart
    - lib/app/utils/translations/generated/intl/*.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/injectable.config.dart
    - test/**/*.mocks.dart
    - test/generate_mocks.mocks.dart

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - sort_constructors_first
    - prefer_relative_imports
    - directives_ordering