name: flash_cards
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #native_splash
  flutter_native_splash: ^2.1.2+1

  # database
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # auto_route
  auto_route: ^5.0.4

  # immutable_classes
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  # serialization
  json_serializable: ^6.0.0
  json_annotation: ^4.4.0

  # http client
  dio: ^4.0.0
  retrofit: ^3.0.1+1
  pretty_dio_logger: ^1.1.1

  # dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # internationalization and localization
  intl: ^0.17.0
  intl_utils: ^2.4.1
  flutter_localizations:
    sdk: flutter

  # ephemeral state
  flutter_hooks: ^0.18.2+1

  # ui
  flutter_svg: ^1.0.3

  # functional programming
  dartz: ^0.10.0

  # business logic
  flutter_bloc: ^8.0.1

  # firebase
  firebase_core: ^2.4.0
  firebase_messaging: 14.2.0
  firebase_analytics: 10.0.8
  firebase_crashlytics: ^3.0.8
  firebase_auth: ^4.2.3
  firebase_database: ^10.0.8
  cloud_firestore: ^4.3.0

  #secure storage
  flutter_secure_storage: ^7.0.1

  #fonts
  google_fonts: ^3.0.1

  #indicators
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2

  #animations
  animations: ^2.0.2

  #Testing
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.0.1
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  build_runner: ^2.1.4
  analyzer: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/images/png/

  fonts:
    - family: Joan
      fonts:
        - asset: lib/app/assets/fonts/Joan-Regular.ttf
          weight: 400
    - family: PermanentMarker
      fonts:
        - asset: lib/app/assets/fonts/PermanentMarker-Regular.ttf
          weight: 400
    - family: PlayfairDisplay
      fonts:
        - asset: lib/app/assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
flutter_intl:
  enabled: true
  class_name: Translation
  main_locale: pl
  arb_dir: lib/app/utils/translation/l10n
  output_dir: lib/app/utils/translation/generated
