name: flash_cards
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.13.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #native_splash
  flutter_native_splash: ^2.1.2+1

  # auto_route
  auto_route: ^7.8.2

  # immutable_classes
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

  # serialization
  json_serializable: ^6.0.0
  json_annotation: ^4.4.0

  # http client
  dio: ^5.3.2
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.1.1

  # dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # internationalization and localization
  intl: ^0.18.0
  intl_utils: ^2.8.4
  flutter_localizations:
    sdk: flutter

  # ephemeral state
  flutter_hooks: ^0.20.1

  # ui
  flutter_svg: ^2.0.7

  # functional programming
  dartz: ^0.10.0

  # business logic
  flutter_bloc: ^8.1.3

  # firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.0.8
  firebase_auth: ^4.2.3
  firebase_database: ^10.0.8
  cloud_firestore: ^4.3.0

  #secure storage
  flutter_secure_storage: ^9.0.0

  #fonts
  google_fonts: ^6.1.0

  #indicators
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2

  #animations
  animations: ^2.0.2

  flutter_gen: ^5.3.2
  flutter_animate: ^4.2.0+1
  equatable: ^2.0.5
  gap: ^3.0.1
  country_picker: ^2.0.22
  country_flags: ^2.1.1
  translator_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.1
  retrofit_generator: ^8.0.4
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  analyzer: ^5.0.0

  # testing
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  golden_toolkit: ^0.15.0
  fake_cloud_firestore: ^2.4.3
  alchemist: ^0.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/png/

  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
          weight: 400
    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/gloria_hallelujah/GloriaHallelujah-Regular.ttf
          weight: 400
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  class_name: Translation
  main_locale: pl
  arb_dir: lib/app/utils/translation/l10n
  output_dir: lib/app/utils/translation/generated
